const NAVIGATOR = {
    START: 'NAVIGATOR_START',
    LOGIN: 'NAVIGATOR_LOGIN',
    LOGINUSER: 'NAVIGATOR_LOGIN_USER',
    DRAWER: 'NAVIGATOR_DRAWER',
  };
  const LOGIN_STACK = {
    LOGIN: 'LOGIN',
    REGISTER: 'REGISTER',
    PASSWORD_RECOVERY: 'PASSWORD_RECOVERY',
  };

  const PASSWORD_STACK = {
    ASKEMAIL: 'ASKEMAIL',
    ASKTOKEN: 'ASKTOKEN',
    CHANGE_PASSWORD: 'CHANGE_PASSWORD',
  };
  const LANDING_STACK = {
    RESTAURANT: 'RESTAURANT',
    NEW_RESTAURANT:'NEW_RESTAURANT',
    FAVORITES: 'FAVORITES',
  };
  const TAB_STACK = {
    RESTAURANTS: 'TAB_RESTAURANTS',
    FAVORITES: 'TAB_FAVORITES',
    PROFILE: 'TAB_PROFILE',
  };
  const DRAWER_SCREEN = {
    PROFILE: 'PROFILE',
  };
  
  export default {
    NAVIGATOR,
    LOGIN_STACK,
    LANDING_STACK,
    TAB_STACK,
    DRAWER_SCREEN,
    PASSWORD_STACK,
  };

  