const NAVIGATOR = {
    START: 'NAVIGATOR_START',
    LOGIN: 'NAVIGATOR_LOGIN',
    LOGINUSER: 'NAVIGATOR_LOGIN_USER',
    DRAWER: 'NAVIGATOR_DRAWER',
  };
  const LOGIN_STACK = {
    LOGIN: 'LOGIN',
    REGISTER: 'REGISTER',
    PASSWORD_RECOVERY: 'PASSWORD_RECOVERY',
  };

  const PASSWORD_STACK = {
    ASKEMAIL: 'ASKEMAIL',
    ASKTOKEN: 'ASKTOKEN',
    CHANGE_PASSWORD: 'CHANGE_PASSWORD',
  };
  const LANDING_STACK = {
    RESTAURANT: 'RESTAURANT',
    NEW_RESTAURANT:'NEW_RESTAURANT',
    FAVORITES: 'FAVORITES',
    PROFILE: 'PROFILE',
    RESTAURANT_DETAILS: "RESTAURANT_DETAILS",
  };
  const PROFILE_STACK = {
    PROFILE: 'PROFILE',
    INFORMATION: 'INFORMATION',
    CHANGE_PASSWORD: 'CHANGE_PASSWORD',
    LOG_OFF: 'LOG_OFF',
  };
  const NEW_RESTAURANT_STACK = {
    SCREEN_2: 'SCREEN_2',
    NEW_MEAL:'NEW_MEAL'
  };
  const TAB_STACK = {
    RESTAURANTS: 'TAB_RESTAURANTS',
    FAVORITES: 'TAB_FAVORITES',
    PROFILE: 'TAB_PROFILE',
  };
  const DRAWER_SCREEN = {
    PROFILE: 'PROFILE',
  };

  const CLIENT_STACK = {
    REGISTER_CLIENT: 'REGISTER_CLIENT',
    CLIENT_NEAR_BY: 'CLIENT_NEAR_BY',
    CLIENT_INFORMATION: 'CLIENT_INFORMATION',
    CLIENT_INFORMATION_SETTINGS: 'CLIENT_INFORMATION_SETTINGS',
    CLIENT_CHANGE_PASSWORD:'CLIENT_CHANGE_PASSWORD',
  };
  
  export default {
    NAVIGATOR,
    LOGIN_STACK,
    LANDING_STACK,
    TAB_STACK,
    DRAWER_SCREEN,
    PASSWORD_STACK,
    PROFILE_STACK,
    NEW_RESTAURANT_STACK,
    CLIENT_STACK
  };

  